version: '3'
services:
  web:
    image: criscun/mipagina-nginx:latest 
    container_name: pagina-nginx 
    ports:
    - "8787:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html 
      - ./assets:/usr/share/nginx/html/assets 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf